---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tm7ojzzmbknt/public_html/
    - /home/tm7ojzzmbknt/repositories/elaine/web -R web $DEPLOYPATH
    - /home/tm7ojzzmbknt/repositories/elaine/vendor -R vendor $DEPLOYPATH
    - /home/tm7ojzzmbknt/repositories/elaine/scripts -R scripts $DEPLOYPATH
    - /home/tm7ojzzmbknt/repositories/elaine/config -R config $DEPLOYPATH
