---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tm7ojzzmbknt/public_html
    - /bin/cp -R web $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
