---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tm7ojzzmbknt/public_html/
    - /home/tm7ojzzmbknt/repositories/elaine -R web $DEPLOYPATH
    - /home/tm7ojzzmbknt/repositories/elaine -R vendor $DEPLOYPATH
    - /home/tm7ojzzmbknt/repositories/elaine -R scripts $DEPLOYPATH
    - /home/tm7ojzzmbknt/repositories/elaine -R config $DEPLOYPATH
